[package]
name = "kilnonedre-common-grpc"
edition.workspace = true
version.workspace = true

[dependencies]
tonic = { workspace = true }
prost = { workspace = true }
tonic-prost = { workspace = true }
once_cell = { workspace = true }
tokio = { workspace = true }
log = { workspace = true }
uuid = { workspace = true }
sea-orm = { workspace = true }

[build-dependencies]
tonic-prost-build = { workspace = true }
