syntax = "proto3";

package procurement.v1;

service GrpcProcurementSupplierService {
  rpc BatchRead(GrpcProcurementSupplierServiceBatchReadRequest) returns (GrpcProcurementSupplierServiceBatchReadResponse);
}

// 批量读取请求
message GrpcProcurementSupplierServiceBatchReadRequest {
  // ID 列表
  repeated string ids = 1;
}

// 批量读取响应
message GrpcProcurementSupplierServiceBatchReadResponse {
  // 列表
  repeated GrpcProcurementSupplierServiceSupplierResponse suppliers = 1;
}

// 信息
message GrpcProcurementSupplierServiceSupplierResponse {
  // 供应商 ID
  string id = 1;

  // 名称
  string name = 2;

  // 编码
  optional string code = 3;

  // 员工资料 ID
  string seller_profile_id = 4;

  // 定位 ID
  string location_id = 5;

  // 详细地址
  optional string location_detail = 6;

  // 资质文件 ID 列表
  repeated string certificate_ids = 7;
}
