[package]
name = "kilnonedre-common-util"
edition.workspace = true
version.workspace = true

[dependencies]
kilnonedre-common-grpc = { workspace = true }
kilnonedre-common-type = { workspace = true }
kilnonedre-common-web = { workspace = true }
kilnonedre-common-misc = { workspace = true }

uuid = { workspace = true }
log = { workspace = true }
sea-orm = { workspace = true }
rust_decimal = { workspace = true }
