[package]
name = "common-util"
edition.workspace = true
version.workspace = true

[dependencies]
common-grpc = { workspace = true }
common-type = { workspace = true }
common-web = { workspace = true }
common-misc = { workspace = true }

uuid = { workspace = true }
log = { workspace = true }
sea-orm = { workspace = true }
rust_decimal = { workspace = true }
