syntax = "proto3";

package catalog.v1;

service GrpcCatalogProductService {
  // 批量读取
  rpc BatchRead(GrpcCatalogProductServiceBatchReadRequest) returns (GrpcCatalogProductServiceBatchReadResponse);
}

// 批量读取请求
message GrpcCatalogProductServiceBatchReadRequest {
  // ID 列表
  repeated string ids = 1;
}

// 批量读取响应
message GrpcCatalogProductServiceBatchReadResponse {
  // 响应列表
  repeated GrpcCatalogProductServiceProductResponse products = 1;
}

// 信息
message GrpcCatalogProductServiceProductResponse {
  // ID
  string id = 1;

  // 名称
  string name = 2;

  // 编码
  string code = 3;

  // 别名
  optional string alias = 4;

  // 备注
  optional string remark = 5;
}
