syntax = "proto3";

package catalog.v1;

import "catalog/v1/common.proto";
import "catalog/v1/product.proto";

service GrpcCatalogProductSpuService {
  // 批量读取
  rpc BatchRead(GrpcCatalogProductSpuServiceBatchReadRequest) returns (GrpcCatalogProductSpuServiceBatchReadResponse);
}

// 批量读取请求
message GrpcCatalogProductSpuServiceBatchReadRequest {
  // ID 列表
  repeated string ids = 1;
}

// 批量读取响应
message GrpcCatalogProductSpuServiceBatchReadResponse {
  // 响应列表
  repeated GrpcCatalogProductSpuServiceProductSpuResponse product_spus = 1;
}

// 信息
message GrpcCatalogProductSpuServiceProductSpuResponse {
  // ID
  string id = 1;

  // 商品
  GrpcCatalogProductServiceProductResponse product = 2;

  // 名称
  string name = 3;

  // 编码
  string code = 4;

  // 分类
  repeated GrpcCatalogProductSpuCategory categories = 5;

  // 标签
  repeated GrpcCatalogProductSpuTag tags = 6;

  // 采购类型
  GrpcCatalogProcurementType procurement_type = 7;

  // 采购员 ID
  optional string purchaser_id = 8;

  // 供应商 ID
  optional string supplier_id = 9;

  // 采购负责人 ID
  string purchaser_manager_id = 10;

  // 是否为标品
  bool is_standard = 11;

  // 地址
  optional string location_id = 12;

  // 详细地址
  optional string location_detail = 13;

  // 储藏方式
  GrpcCatalogStorageMethod storage_method = 14;

  // 封面 ID
  repeated string cover_ids = 15;

  // 详情图 ID
  repeated string detail_image_ids = 16;

  // 备注
  optional string remark = 17;
}

// 商品 SPU 标签
message GrpcCatalogProductSpuTag {
  // ID
  string id = 1;

  // 名称
  string name = 2;
}

// 商品 SPU 分类
message GrpcCatalogProductSpuCategory {
  // ID
  string id = 1;

  // 父分类 ID
  optional string parent_id = 2;

  // 名称
  string name = 3;

  // 层级
  int32 level = 4;

  // 排序
  optional int32 sort = 5;

  // 是否叶子节点
  optional bool is_leaf = 6;

  // 图片 ID
  optional string image_id = 7;
}
