[package]
name = "kilnonedre-common-misc"
edition.workspace = true
version.workspace = true

[dependencies]
kilnonedre-common-web = { workspace = true }
kilnonedre-common-type = { workspace = true }
kilnonedre-common-grpc = { workspace = true }
kilnonedre-common-config = { workspace = true }

sea-orm = { workspace = true }
local-ip-address = { workspace = true }
once_cell = { workspace = true }
regex = { workspace = true }
actix-web = { workspace = true }
log = { workspace = true }
uuid = { workspace = true }
rust_decimal = { workspace = true }
tonic = { workspace = true }
tokio = { workspace = true }
tokio-cron-scheduler = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
rand = { workspace = true }
chrono = { workspace = true }
