syntax = "proto3";

package logistics.v1;

service GrpcLogisticsAreaService {
  // 批量读取
  rpc BatchRead(GrpcLogisticsAreaServiceBatchReadRequest) returns (GrpcLogisticsAreaServiceBatchReadResponse);
}

// 批量读取请求
message GrpcLogisticsAreaServiceBatchReadRequest {
  // ID 列表
  repeated string ids = 1;
}

// 批量读取响应
message GrpcLogisticsAreaServiceBatchReadResponse {
  // 响应列表
  repeated GrpcLogisticsAreaServiceAreaResponse areas = 1;
}

// 区域信息
message GrpcLogisticsAreaServiceAreaResponse {
  // ID
  string id = 1;

  // 名称
  string name = 2;

  // 编码
  optional string code = 3;
}
