syntax = "proto3";

package logistics.v1;

service GrpcLogisticsCarService {
  // 批量读取
  rpc BatchRead(GrpcLogisticsCarServiceBatchReadRequest) returns (GrpcLogisticsCarServiceBatchReadResponse);
}

// 批量读取请求
message GrpcLogisticsCarServiceBatchReadRequest {
  // ID 列表
  repeated string ids = 1;
}

// 批量读取响应
message GrpcLogisticsCarServiceBatchReadResponse {
  // 响应列表
  repeated GrpcLogisticsCarServiceCarResponse cars = 1;
}

// 车辆信息
message GrpcLogisticsCarServiceCarResponse {
  // ID
  string id = 1;

  // 车牌号
  string plate_no = 2;

  // 额定载重
  string capacity_weight = 3;

  // 指定容积
  string capacity_volume = 4;
}
