syntax = "proto3";

package logistics.v1;

import "logistics/v1/car.proto";

service GrpcLogisticsDriverService {
  // 批量读取
  rpc BatchRead(GrpcLogisticsDriverServiceBatchReadRequest) returns (GrpcLogisticsDriverServiceBatchReadResponse);
}

// 批量读取请求
message GrpcLogisticsDriverServiceBatchReadRequest {
  // ID 列表
  repeated string ids = 1;
}

// 批量读取响应
message GrpcLogisticsDriverServiceBatchReadResponse {
  // 响应列表
  repeated GrpcLogisticsDriverServiceDriverResponse drivers = 1;
}

// 驾驶员信息
message GrpcLogisticsDriverServiceDriverResponse {
  // ID
  string id = 1;

  // 员工资料
  string seller_profile_id = 2;

  // 车辆
  optional GrpcLogisticsCarServiceCarResponse car = 3;

  // 驾驶证号码
  string driving_license_no = 4;

  // 附件
  repeated string certificate_ids = 5;
}
