syntax = "proto3";

package logistics.v1;

import "logistics/v1/area.proto";
import "logistics/v1/driver.proto";

service GrpcLogisticsRouteService {
  // 批量读取
  rpc BatchRead(GrpcLogisticsRouteServiceBatchReadRequest) returns (GrpcLogisticsRouteServiceBatchReadResponse);
}

// 批量读取请求
message GrpcLogisticsRouteServiceBatchReadRequest {
  // 定位 ID 列表
  repeated string ids = 1;
}

// 批量读取响应
message GrpcLogisticsRouteServiceBatchReadResponse {
  // 定位列表
  repeated GrpcLogisticsRouteServiceRouteResponse routes = 1;
}

// 路线信息
message GrpcLogisticsRouteServiceRouteResponse {
  // 定位 ID
  string id = 1;

  // 区域 ID
  GrpcLogisticsAreaServiceAreaResponse area = 2;

  // 路线名称
  string name = 3;

  // 路线名称
  optional string color = 4;

  // 备注
  optional string remark = 5;

  // 司机 ID
  GrpcLogisticsDriverServiceDriverResponse driver = 6;
}
