[package]
name = "kilnonedre-common-db"
version.workspace = true
edition.workspace = true

[dependencies]
kilnonedre-common-type = { workspace = true }
kilnonedre-common-web = { workspace = true }
kilnonedre-common-config = { workspace = true }

sea-orm = { workspace = true }
tokio = { workspace = true }
log = { workspace = true }
