[package]
name = "common-type"
edition.workspace = true
version.workspace = true

[dependencies]
common-grpc = { workspace = true }

serde = { workspace = true }
utoipa = { workspace = true }
sea-orm = { workspace = true }
actix-web = { workspace = true }
common-web = { workspace = true }
rust_decimal = { workspace = true }
tonic = { workspace = true }
uuid = { workspace = true }
