[package]
name = "kilnonedre-common-type"
edition.workspace = true
version.workspace = true

[dependencies]
kilnonedre-common-grpc = { workspace = true }
kilnonedre-common-web = { workspace = true }

serde = { workspace = true }
utoipa = { workspace = true }
sea-orm = { workspace = true }
actix-web = { workspace = true }
rust_decimal = { workspace = true }
tonic = { workspace = true }
uuid = { workspace = true }
